import sys
import os

# Add backend directory to sys.path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app.services.report_service import generate_pdf

if __name__ == "__main__":
    try:
        pdf_bytes = generate_pdf(
            markdown_text="# Test Report\n\nThis is a test.",
            title="Test",
            filename="test.csv",
            findings_count=1,
            chart_paths=[]
        )
        print("Success! Generated bytes:", len(pdf_bytes))
    except Exception as e:
        import traceback
        traceback.print_exc()
