"""
Reporter Agent — LangGraph node.
Synthesizes all findings into a comprehensive Markdown report.
"""

import time
from datetime import datetime, timezone
from langchain_core.messages import HumanMessage, SystemMessage

from app.agents.state import AnalysisState
from app.agents.llm_client import get_creative_llm
from app.agents.utils import make_step_record, summarise_findings, extract_text_from_response
from app.agents.prompts.report_prompt import REPORT_SYSTEM, REPORT_USER_TEMPLATE


def reporter_node(state: AnalysisState) -> AnalysisState:
    """Synthesize all findings into a comprehensive Markdown report."""
    start = time.time()
    agent_name = "reporter"
    step_index = len(state.get("step_records", []))

    profile = state.get("dataset_profile", {})
    all_findings = state.get("findings", [])
    step_records = state.get("step_records", [])

    # Calculate total analysis duration
    total_duration = sum(s.get("duration_seconds", 0) for s in step_records)

    # Separate findings by type
    stats_findings = [f for f in all_findings if f["agent_name"] == "statistician"]
    stats_summary = summarise_findings(stats_findings, max_chars=4000)
    all_findings_text = summarise_findings(all_findings, max_chars=8000)

    try:
        user_msg = REPORT_USER_TEMPLATE.format(
            dataset_filename=state.get("dataset_filename", "dataset"),
            rows=profile.get("rows", "?"),
            columns=profile.get("columns", "?"),
            duration=f"{total_duration:.1f} seconds",
            user_query=state.get("user_query", "Comprehensive data analysis"),
            all_findings_text=all_findings_text or "No specific findings were generated.",
            stats_summary=stats_summary or "No statistical tests were run.",
        )

        llm = get_creative_llm()
        response = llm.invoke([
            SystemMessage(content=REPORT_SYSTEM),
            HumanMessage(content=user_msg),
        ])
        report_md = extract_text_from_response(response.content).strip()

        step = make_step_record(
            agent_name=agent_name,
            step_index=step_index,
            status="completed",
            message=f"Report generated: {len(report_md)} characters",
            code_output=report_md[:500] + "..." if len(report_md) > 500 else report_md,
            duration_seconds=round(time.time() - start, 2),
            output_data={"report_length": len(report_md)},
        )

        return {
            **state,
            "report_markdown": report_md,
            "current_agent": "done",
            "step_records": state.get("step_records", []) + [step],
        }

    except Exception as e:
        # Fallback: write a minimal report from findings
        fallback = _generate_fallback_report(state, all_findings_text, total_duration)
        step = make_step_record(
            agent_name=agent_name,
            step_index=step_index,
            status="failed",
            message="Reporter used fallback due to LLM error",
            error_message=str(e),
            duration_seconds=round(time.time() - start, 2),
        )
        return {
            **state,
            "report_markdown": fallback,
            "current_agent": "done",
            "error_count": state.get("error_count", 0) + 1,
            "step_records": state.get("step_records", []) + [step],
        }


def _generate_fallback_report(state: AnalysisState, findings_text: str, duration: float) -> str:
    """Minimal fallback report when LLM call fails."""
    profile = state.get("dataset_profile", {})
    return f"""# {state.get("dataset_filename", "Dataset")} — Analytical Report

**Generated**: {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}
**Dataset**: {profile.get("rows", "?")} rows × {profile.get("columns", "?")} columns
**Analysis Duration**: {duration:.1f}s
**User Query**: {state.get("user_query", "N/A")}

## Key Findings

{findings_text or "No findings were collected during this analysis."}

## Charts

{len(state.get("chart_paths", []))} visualizations were generated and stored.

---
*Report generated by the Autonomous Data Analyst Agent.*
"""
